---
title: Proyecto de AED
author:
  - name: Joan Merlos Cremades
    affil: 1,*
  - name: Héctor Torres Muñoz
    affil: 2
affiliation:
  - num: 1
    address:
      Universitat de València
    email: joanmer@alumni.uv.es
  - num: 2
    address:
      Universitat de València
    email: hecto2@alumni.uv.es
correspondence:
  joanmer@alumni.uv.es
# document options
journal: notspecified
type: article
status: submit
# front matter
simplesummary: |
  Proyecto de la asignatura Ánalisis exploratorio de datos del Máster en Ciencia de datos de la Universitat de València.
abstract: |
  En las siguientes páginas se encuentra ...
keywords: |
  Análisis exploratorio de datos, INE, Inserción laboral.
bibliography: mybibfile.bib
endnotes: false
output: 
  rticles::mdpi_article:
    extra_dependencies: longtable
---

# Importación de los datos

En este apartado vamos a proceder a importar el archivo de datos con el que vamos a trabajar, el cual pertenece al INE (Insituto Nacional de Estadística) y trata sobre la inserción laboral de las personas con estudios universitarios o superiores.


Importamos los datos:
```{r}
library(readr)
df_raw <- read_delim("./data/EILU_GRAD_2019.csv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)
```

Seleccionamos las variables de interés:
```{r}
var <- c('IDENT','SEXO','EDAD','TITU','AMBITO','T_UNIV','EST_B12','EST_B16',
         'EST_B13_AMB1','EST_B13_AMB2','EST_B13_AMB3','EST_B17_M1','EST_B17_M2',
         'EST_B17_M3','EST_B21','EST2_SA','EST2_NC','IDIOMAS','SIT_PRO','TR_SUELDO',
         'HATR_E11')

df <- df_raw[var]
```

